sudo: required
dist: trusty
language: rust
cache:
    directories:
        - .vagga/stable-home
        - .vagga/beta-home
        - .vagga/nightly-home

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

env:
  matrix:
  - FEATURES=""
  - FEATURES="static"
  - FEATURES="wayland"
  - FEATURES="render"
  - FEATURES="serialization"
  - FEATURES="static wayland"
  - FEATURES="static render"
  - FEATURES="static serialization"
  - FEATURES="wayland render"
  - FEATURES="wayland serialization"
  - FEATURES="render serialization"
  - FEATURES="static render wayland"
  - FEATURES="static render serialization"
  - FEATURES="static wayland serialization"
  - FEATURES="render wayland serialization"
  - FEATURES="static render wayland serialization"
  global:
  - secure: LfrkRn+N3DVHLHuVFX1RB2clpfQ6IwipiRRwB0Kg7ARM/rMhS5L3kM98PUQ5u+X3mgfxn93whAHtIh3S4oNQOWYMgYBYPNaFaGbV4zkEeKyAvU5cl8AzAuyH+hSx/x/njh8A0Z2Ki90lM/8rPHuU4VIudcunR9WvUkbwglRfZfcfQZY/I5PJ2rwWNBvsYopMv1o2kU0oFqEm89MIL6H7WpH02w1oWDiE+EQAQDYEsoqcxJayblNkikSLEH1zJouP5F1exN6j5gsnapHr2bVDBGNw9o6He5idK3iMaUaFjtqgDF+/Wlci1v1+FnQnX11691aR1pzpBA3KrQry8IeLtR6s7THWnr6/zWRbqKGzhN6mXGHy/yWPlg+ade2333i6qHa/KxQDvt7/S1mSBtwtvCgr7VIMLo5C3n7TDY0H0+WkjlqVQz2iIB272OOGct6XQkjoG1V3xWm2DjjQo4GVT619DsF8ZiMTeJUD86Rix5kLu9XVvxlIHey7EQwM838e2r9U+a3XdQPixkTV4c9zZnE+t3ZyHSMdIUu2GFNfgjyCHBtj80f1E42npIPFp6JSEbBcvkqpp4ggRAuFMOrmdD79YvGDPXEp9GshXUvnZ6X0c/mN5Cfro9JvPGkC6fmKRMP+RZW7WpWvIpJuO91FL+6xFIlZmq5yQBPROx22FTE=

before_script:
- "echo ubuntu-mirror: http://mirrors.us.kernel.org/ubuntu/ > ~/.vagga.yaml"
- "echo alpine-mirror: http://mirrors.gigenet.com/alpinelinux/ >> ~/.vagga.yaml"
- |
    echo "$(id -un):100000:65536" | sudo tee /etc/subuid | sudo tee /etc/subgid
    sudo apt-get install uidmap -y
    curl http://files.zerogw.com/vagga/vagga-install-testing.sh | sh
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

script:
- vagga check-fmt
- vagga clippy "$FEATURES"
- |
    if [[ $FEATURES != *"serialization"* ]]; then
        vagga build-stable "unsafe-stable $FEATURES"
        vagga build-example-stable "unsafe-stable $FEATURES"
        vagga test-stable "unsafe-stable $FEATURES"
    fi

- vagga build-beta "unsafe-stable $FEATURES"
- vagga build-example-beta "unsafe-stable $FEATURES"
- vagga test-beta "unsafe-stable $FEATURES"
- vagga build-nightly "$FEATURES"
- vagga build-example-nightly "$FEATURES"
- vagga test-nightly "$FEATURES"
- |
    if [ "$FEATURES" == "static render wayland serialization" ]
    then
      vagga doc "$FEATURES"
    fi

after_success:
- |
    if [ $FEATURES == "static render wayland serialization" ]
    then
      travis-cargo doc-upload
    fi
