[package]
name = "wlc-sys"
version = "0.0.7"
authors = ["Victor Brekenfeld (Drakulix) <github@drakulix.de>"]
build = "build.rs"

[lib]
path = "src/lib.rs"

[build-dependencies]
bindgen = "0.20"
cmake = { version = "0.1", optional = true }

[dependencies]
libc = "0.2"

[features]
static = ["cmake"]
